import type { Metadata } from "next";




import React from "react";


export const metadata: Metadata = {
            title: "SignIn",
            description: "Generated by create next app",
};

export default function RootLayout({
            children,
}: {
            children: React.ReactNode,

}) {


            return (
                       <>
                                    {children}
                       </>
            );
}
